### ISSUE TITLE
Melonds

### ISSUE THREAD

**Issue by zhanghaono** [spleen1981/retroarch-kodi-addon-CoreELEC#10]
Nintendo-DS melonds
failed to open libretro core

**Comment by spleen1981** [comment]
Can you share a verbose log?

**Comment by zhanghaono** [comment]
but /retroarch/logs/ not files

**Comment by zhanghaono** [comment]
[INFO] [Config]: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.14.0 (Git ad89b0c)
[INFO] === Build =======================================
[INFO] CPU Model Name: Amlogic S905X3 rev b

[INFO] 容量: NEON ASIMD
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: ad89b0c
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] GLES version = 2.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Created shared context: 0xd5cfd0.
[INFO] [EGL]: Current context: 0xd0c798.
[INFO] [GL]: Found GL context: "fbdev_mali".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-G31.
[INFO] [GL]: Version: OpenGL ES 3.2 git.c8adbf9.cd625e29b5da737db5b7abc88e423a3b.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: udev_input_add_device error : /dev/input/event7 (Success).
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Keyboard #0: "input_btrcu" (/dev/input/event3).
[INFO] [udev]: Keyboard #1: "gpio_keypad" (/dev/input/event0).
[INFO] [udev]: Keyboard #2: "meson-ir" (/dev/input/event6).
[INFO] [udev]: Keyboard #3: "aml_vkeypad" (/dev/input/event1).
[INFO] [udev]: Keyboard #4: "vad_keypad" (/dev/input/event4).
[INFO] [udev]: Keyboard #5: "cec_input" (/dev/input/event2).
[INFO] [udev]: Keyboard #6: "VNCServer SimKey" (/dev/input/event7).
[INFO] [udev]: Pad #0 (/dev/input/event5) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event5) supports 16 force feedback effects.
[INFO] [Autoconf]: Microsoft X-Box 360 pad (1118/654) 未配置.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[WARN] [udev]: Mouse grab/ungrab feature unavailable.
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "/storage/.config/retroarch/content_favorites.lpl".
[INFO] [Config]: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.14.0 (Git ad89b0c)
[INFO] === Build =======================================
[INFO] CPU Model Name: Amlogic S905X3 rev b

[INFO] 容量: NEON ASIMD
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: ad89b0c
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] GLES version = 2.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Created shared context: 0xfd5fd0.
[INFO] [EGL]: Current context: 0xf85798.
[INFO] [GL]: Found GL context: "fbdev_mali".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-G31.
[INFO] [GL]: Version: OpenGL ES 3.2 git.c8adbf9.cd625e29b5da737db5b7abc88e423a3b.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initiali

**Comment by zhanghaono** [comment]
[INFO] RetroArch 1.14.0 (Git ad89b0c)
[INFO] === Build =======================================
[INFO] CPU Model Name: Amlogic S905X3 rev b

[INFO] 容量: NEON ASIMD
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: ad89b0c
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: libretro API 版本: 1, 未按照 API 编译: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] GLES version = 2.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Created shared context: 0x1d27390.
[INFO] [EGL]: Current context: 0x1cd6b58.
[INFO] [GL]: Found GL context: "fbdev_mali".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-G31.
[INFO] [GL]: Version: OpenGL ES 3.2 git.c8adbf9.cd625e29b5da737db5b7abc88e423a3b.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: udev_input_add_device error : /dev/input/event7 (Success).
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Keyboard #0: "input_btrcu" (/dev/input/event3).
[INFO] [udev]: Keyboard #1: "gpio_keypad" (/dev/input/event0).
[INFO] [udev]: Keyboard #2: "meson-ir" (/dev/input/event6).
[INFO] [udev]: Keyboard #3: "aml_vkeypad" (/dev/input/event1).
[INFO] [udev]: Keyboard #4: "vad_keypad" (/dev/input/event4).
[INFO] [udev]: Keyboard #5: "cec-mini-kb" (/dev/input/event8).
[INFO] [udev]: Keyboard #6: "cec_input" (/dev/input/event2).
[INFO] [udev]: Keyboard #7: "VNCServer SimKey" (/dev/input/event7).
[INFO] [udev]: Pad #0 (/dev/input/event5) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event5) supports 16 force feedback effects.
[INFO] [Autoconf]: Microsoft X-Box 360 pad (1118/654) 未配置.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[WARN] [udev]: Mouse grab/ungrab feature unavailable.
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: 正在读取历史文件: "/storage/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: 正在加载收藏文件: "/storage/.config/retroarch/content_favorites.lpl".
[ERROR] 打开libretro核心失败: "/storage/.kodi/addons/script.retroarch.launcher.Amlogic-ng.arm/lib/libretro/melonds_libretro.so"
[ERROR] Error(s): libGL.so.1: cannot open shared object file: No such file or directory
[INFO] [Core]: Using content: "/storage/emuroms/nds/Mario endlessearth.nds".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

**Comment by zhanghaono** [comment]
[ERROR] 打开libretro核心失败: "/storage/.kodi/addons/script.retroarch.launcher.Amlogic-ng.arm/lib/libretro/melonds_libretro.so"
[ERROR] Error(s): libGL.so.1: cannot open shared object file: No such file or directory

**Comment by spleen1981** [comment]
fixed by a941cc007fcf66c3408698f19cd61cfdfbdf9ac6 and a25713effe13ab88e17aeb13b8db2a9c80447b5e
