### ISSUE TITLE
no sound on Beelink GT-King (s922x ver b)

### ISSUE THREAD

**Issue by VergilGao** [spleen1981/retroarch-kodi-addon-CoreELEC#15]
The sound plays fine in kodi, but there is no sound inside the retroarch.

**Comment by spleen1981** [comment]
is "Sync RetroArch audio driver/device with Kodi" setting enabled in the addon options?

**Comment by VergilGao** [comment]
yes im trying on change the kodi audio settings to see any improvement

**Comment by VergilGao** [comment]
i changed some kodi settings about stereo and the sound works in retroarch.

**Comment by biaji** [comment]
> i changed some kodi settings about stereo and the sound works in retroarch.

Would you please tell me which one to check?  I'm facing the same situation.
