### ISSUE TITLE
Some accented characters are displayed as "?"

### ISSUE THREAD

**Issue by jose1711** [spleen1981/retroarch-kodi-addon-CoreELEC#16]
Language set to Slovak, fresh install. Instead of "Načítať obsah" you'll get "Na?íta? obsah" in the menu etc. Clearly an issue with bitmap font (https://raw.githubusercontent.com/libretro/RetroArch/master/gfx/drivers_font_renderer/bitmap.bmp) not covering all the characters but I do wonder if there is any solution. Thank you!

**Comment by spleen1981** [comment]
It looks like you need to download assets, go to retroarch menu > online updater and download assets and other stuff as needed.

**Comment by jose1711** [comment]
Thank you, that indeed fixed it. Would it be worth updating the sentence "By default the add-on includes only RetroArch and cores to reduce the zip size, use RetroArch internal online updater to download resources as needed."? Perhaps just make it a *strong recommendation*?

**Comment by spleen1981** [comment]
I've added a check on addon launch which will advise the user with a dialog, in case of assets missing 3874cb16e2a7863716d712b99cae4c8e37c06a3b
