### ISSUE TITLE
Segmentation Fault on S905X4 when try to 

### ISSUE THREAD

**Issue by turric4n** [spleen1981/retroarch-kodi-addon-CoreELEC#27]
Hi,

I'm getting segfault when I select Load Content option in Retroarch menu :

`./retroarch.start: line 306: 22060 Segmentation fault      (core dumped) $RA_EXE $RA_PARAMS "$@"`

I don't have any idea what issue can be. I'm using an Amlogic S905X4 with the following CoreElec image :

```
CoreELEC (official): 22.0-Piers_nightly_20241128 (Amlogic-no.aarch64)
      Machine model: Amlogic
     CoreELEC dt-id: sc2_s905x4_4g
      Linux version: 5.15.119 (docker@95cdcaaf0dc8) #1 Thu Nov 28 01:28:27 IST 2024
      Kodi compiled: 2024-11-28 02:02:42 +0100
```

Here is the crash stacktrace :

`[  374.669165] retroarch[1804]: unhandled exception: DABT (lower EL), ESR 0x92000006, level 2 translation fault in retroarch[400000+a1f000]
[  374.669237] vma for 4e0c34:
[  374.669240] 00400000-00e1f000 r-xp 00000000 b3:12 272680 
[  374.669250] /storage/.kodi/addons/script.retroarch.launcher.Amlogic-no.aarch64/bin/retroarch
[  374.669253] 
[  374.669255] vma for 4e0c2c:
[  374.669257] 00400000-00e1f000 r-xp 00000000 b3:12 272680 
[  374.669264] /storage/.kodi/addons/script.retroarch.launcher.Amlogic-no.aarch64/bin/retroarch
[  374.669266] 
[  374.669268] vma for 18:
[  374.669270] 00400000-00e1f000 r-xp 00000000 b3:12 272680 
[  374.669277] /storage/.kodi/addons/script.retroarch.launcher.Amlogic-no.aarch64/bin/retroarch
[  374.669279] 
[  374.669282] PC : 00000000004e0c34  U
[  374.669287] SP : 0000007ffad1bab0  U
[  374.669290] FAR : 0000000000000018  U
[  374.669294] R10 : ffffffffffa28458, PFN:***** V
[  374.669301] CPU: 3 PID: 1804 Comm: retroarch Tainted: G           O      5.15.119 #1 7025cd8792299fc4d38766b00b85d0640af122eb
[  374.669310] Hardware name: Amlogic (DT)
[  374.669315] pstate: 20001000 (nzCv daif -PAN -UAO -TCO -DIT +SSBS BTYPE=--)
[  374.669321] pc : 00000000004e0c34
[  374.669324] lr : 00000000004e0c2c
[  374.669326] sp : 0000007ffad1bab0
[  374.669330] x29: 0000000000000000 x28: 0000000000000001 x27: 0000000000000000
[  374.669341] x26: 0000000000000000 x25: 0000000000000001 x24: 0000000000000001
[  374.669349] x23: 0000000000000001 x22: 0000000040ebcee0 x21: 0000000000000000
[  374.669358] x20: 0000000000cf0940 x19: 0000007ffad1c5a0 x18: 000000000000ffff
[  374.669366] x17: 0000007f822ce1e4 x16: 00000000004e0520 x15: 0000000041101fb0
[  374.669375] x14: 01111b000a100402 x13: 0000000000000000 x12: 0000000000000006
[  374.669383] x11: 0101010101010101 x10: ffffffffffa28458 x9 : 7f7f7f7f7f7f7f7f
[  374.669392] x8 : 0000000000000001 x7 : 0204100a001b1101 x6 : 0000000000002dc7
[  374.669401] x5 : 00000000004e0520 x4 : 0000000000000000 x3 : 00000000000000b3
[  374.669409] x2 : 0000000000000000 x1 : 0000007ffad1bb38 x0 : 0000000000000000
[  374.669418] 
[  374.669418] PC: 0x4e0bb4:
[  374.669426] 0bb4  3949641c 3949681b 39496c1a 39497017 394af815 39495819 3949f018 540005a0
[  374.669433] 0bd4  7102bedf 12800000 54000461 f9401660 9401469b f9401676 52823da0 97fd48c4
[  374.669439] 0bf4  aa0003f4 52823d60 97fd48c1 aa1403e1 aa0003e2 d2800007 d2800006 d2800005
[  374.669444] 0c14  52801664 52823d63 aa1603e0 940144f0 910223e0 97fe983e f94047e0 b9407be8
[  374.669451] 0c34  f9400c00 b5001380 350015a8 f9401660 52800021 97fcd68a 35001780 34001935
[  374.669456] 0c54  b9404261 52800140 2a000021 52800000 b9004261 a9415bf5 a94263f7 a9436bf9
[  374.669463] 0c74  a94473fb f9402bfe a8c953f3 d65f03c0 b9007be6 97fd03e2 2a0003f6 f9401660
[  374.669468] 0c94  9401466f b9407be6 37880856 b9007be6 97fd02a3 d28b0f01 8b010000 b9407be6
[  374.669470] 
[  374.669470] LR: 0x4e0bac:
[  374.669476] 0bac  b90077e1 39496006 3949641c 3949681b 39496c1a 39497017 394af815 39495819
[  374.669481] 0bcc  3949f018 540005a0 7102bedf 12800000 54000461 f9401660 9401469b f9401676
[  374.669487] 0bec  52823da0 97fd48c4 aa0003f4 52823d60 97fd48c1 aa1403e1 aa0003e2 d2800007
[  374.669492] 0c0c  d2800006 d2800005 52801664 52823d63 aa1603e0 940144f0 910223e0 97fe983e
[  374.669498] 0c2c  f94047e0 b9407be8 f9400c00 b5001380 350015a8 f9401660 52800021 97fcd68a
[  374.669504] 0c4c  35001780 34001935 b9404261 52800140 2a000021 52800000 b9004261 a9415bf5
[  374.669509] 0c6c  a94263f7 a9436bf9 a94473fb f9402bfe a8c953f3 d65f03c0 b9007be6 97fd03e2
[  374.669514] 0c8c  2a0003f6 f9401660 9401466f b9407be6 37880856 b9007be6 97fd02a3 d28b0f01
[  374.669517] 
[  374.669517] SP: 0x7ffad1ba30:
[  374.669522] ba30  000000b3 00000000 000011eb 00000000 00000000 00000000 00cf0940 00000000
[  374.669528] ba50  00000000 00000000 00532188 00000000 fad1c5a0 0000007f 00cf0940 00000000
[  374.669533] ba70  00000000 00000000 40ebcee0 00000000 00000001 00000000 00000001 00000000
[  374.669539] ba90  00000001 00000000 00000000 00000000 00000000 00000000 004e0c24 00000000
[  374.669545] bab0  fad1c5a0 0000007f 40e9f810 00000000 00eca180 00000000 000000af 00000000
[  374.669551] bad0  415302b0 00000000 00000000 00000000 fad1d7b0 0000007f 40ebcee0 00000000
[  374.669557] baf0  00000000 00000000 00ecc180 00000000 00580cf4 00000000 009820a8 00000000
[  374.669562] bb10  822cd66c 0000007f 00000000 00000000 00000001 00000001 00000001 00000001
[  374.669565] 
[  374.669565] FAR: 0x18:
[  374.669597] 0018  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669616] 0038  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669634] 0058  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669653] 0078  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669671] 0098  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669689] 00b8  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669707] 00d8  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669725] 00f8  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669728] 
[  374.669728] r1: 0x7ffad1bab8:
[  374.669734] bab8  40e9f810 00000000 00eca180 00000000 000000af 00000000 415302b0 00000000
[  374.669740] bad8  00000000 00000000 fad1d7b0 0000007f 40ebcee0 00000000 00000000 00000000
[  374.669746] baf8  00ecc180 00000000 00580cf4 00000000 009820a8 00000000 822cd66c 0000007f
[  374.669752] bb18  00000000 00000000 00000001 00000001 00000001 00000001 00000004 00000000
[  374.669758] bb38  00000000 00000000 004e2c7c 00000000 40eb2810 00000000 fad1c5a0 0000007f
[  374.669764] bb58  40eca220 00000000 40e9f810 00000000 412556e0 00000000 00000000 00000000
[  374.669769] bb78  00000001 00000000 41255960 00000000 004e34e4 00000000 6e69614d 6e654d20
[  374.669774] bb98  6e702e75 00000067 0054d6fc 00000000 00000007 00000000 41225dd0 00000000
[  374.669777] 
[  374.669777] r3: 0x33:
[  374.669796] 0030  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669814] 0050  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669832] 0070  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669914] 0090  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669934] 00b0  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669953] 00d0  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669971] 00f0  ******** ******** ******** ******** ******** ******** ******** ********
[  374.669990] 0110  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670008] 0130  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670012] 
[  374.670012] r5: 0x4e04a0:
[  374.670018] 04a0  39400340 34fef760 aa1703e2 aa1a03e0 b00041c1 d2800183 9110a021 97ffd5f5
[  374.670024] 04c0  72001c1f 54000080 52800280 b9004260 17fff7b0 aa1703e2 aa1a03e0 b00041c1
[  374.670030] 04e0  d28001c3 91118021 97ffd5ea 72001c1f 54ff0aa0 528004a0 b9004260 17fff7a5
[  374.670036] 0500  b4000080 9140a000 f94f1000 d65f03c0 d2800000 d65f03c0 d503201f d503201f
[  374.670041] 0520  b4000100 b9428001 340000c1 711d803f 540000c1 90000001 91280021 f9000801
[  374.670048] 0540  52800000 d65f03c0 12800000 d65f03c0 a9bf7bf3 2a0203f3 340001c1 7100043f
[  374.670054] 0560  54000080 d2800000 a8c17bf3 d65f03c0 f9402001 2a0203e2 eb01005f 54ffff42
[  374.670060] 0580  f9401800 a8c17bf3 8b021800 d65f03c0 94014008 f9596800 d2800001 b4000060
[  374.670062] 
[  374.670062] r6: 0x2d47:
[  374.670080] 2d44  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670099] 2d64  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670117] 2d84  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670135] 2da4  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670153] 2dc4  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670171] 2de4  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670190] 2e04  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670208] 2e24  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670226] 2e44  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670231] 
[  374.670231] r15: 0x41101f30:
[  374.670238] 1f30  725f3270 00000033 00000000 00000000 00000020 00000000 00000031 00000000
[  374.670243] 1f50  7074656e 5f79616c 65646166 6168635f 6f745f74 656c6767 6c6c6100 7261635f
[  374.670249] 1f70  41007364 00000000 00000031 00000000 7074654e 2079616c 74736f48 20676e69
[  374.670255] 1f90  676f5428 29656c67 63006400 00666e6f 00666e6f 00000000 00004841 00000000
[  374.670260] 1fb0  00000001 00000000 00e36a20 00000000 411f9dd0 00000000 00000000 00000000
[  374.670265] 1fd0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  374.670270] 1ff0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  374.670275] 2010  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  374.670278] 
[  374.670278] r16: 0x4e04a0:
[  374.670284] 04a0  39400340 34fef760 aa1703e2 aa1a03e0 b00041c1 d2800183 9110a021 97ffd5f5
[  374.670289] 04c0  72001c1f 54000080 52800280 b9004260 17fff7b0 aa1703e2 aa1a03e0 b00041c1
[  374.670295] 04e0  d28001c3 91118021 97ffd5ea 72001c1f 54ff0aa0 528004a0 b9004260 17fff7a5
[  374.670300] 0500  b4000080 9140a000 f94f1000 d65f03c0 d2800000 d65f03c0 d503201f d503201f
[  374.670305] 0520  b4000100 b9428001 340000c1 711d803f 540000c1 90000001 91280021 f9000801
[  374.670311] 0540  52800000 d65f03c0 12800000 d65f03c0 a9bf7bf3 2a0203f3 340001c1 7100043f
[  374.670316] 0560  54000080 d2800000 a8c17bf3 d65f03c0 f9402001 2a0203e2 eb01005f 54ffff42
[  374.670322] 0580  f9401800 a8c17bf3 8b021800 d65f03c0 94014008 f9596800 d2800001 b4000060
[  374.670324] 
[  374.670324] r17: 0x7f822ce164:
[  374.670331] e164  940000c7 aa0003e2 aa1503e1 aa1403e0 38226a9f 94000db2 aa1303e0 a94157f4
[  374.670336] e184  a8c24ffe d65f03c0 d503201f d503201f d503201f d503201f d503201f d503201f
[  374.670341] e1a4  d503201f d503201f d503201f d503201f d503201f d503201f d503201f d503201f
[  374.670347] e1c4  d503201f d503201f d503201f d503201f d503201f d503201f d503201f d503201f
[  374.670352] e1e4  d503201f b4000ea2 ca010008 b200c3eb f240091f 9240080d 54000621 b500030d
[  374.670358] e204  f8408403 f8408424 f1002042 cb0b0068 b200d869 ca040066 da9f80ce ea290105
[  374.670363] e224  fa4009c0 54fffee0 aa0500c7 91002042 dac00ce7 dac00c63 dac010ec dac00c84
[  374.670368] e244  9acc2063 eb4c0c5f 9acc2084 d378fc63 cb44e060 9a9f8000 d65f03c0 927df000
[  374.670371] 
[  374.670371] r18: 0xff7f:
[  374.670390] ff7c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670408] ff9c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670426] ffbc  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670445] ffdc  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670463] fffc  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670481] 001c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670499] 003c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670517] 005c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670535] 007c  ******** ******** ******** ******** ******** ******** ******** ********
[  374.670538] 
[  374.670538] r19: 0x7ffad1c520:
[  374.670544] c520  822cd66c 0000007f 0000000d 00000000 412556e0 00000000 40e9f810 00000000
[  374.670550] c540  412556e0 00000000 415302b0 00000000 00000001 00000000 40eca220 00000000
[  374.670555] c560  00000001 00000000 005327e0 00000000 40eca220 00000000 00eca180 00000000
[  374.670561] c580  41101fb0 00000000 40e9f810 00000000 00000005 00000000 005382f0 00000000
[  374.670566] c5a0  410f1d00 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  374.670571] c5c0  410f1ce0 00000000 40ebcee0 00000000 00000000 00000000 00000000 00000000
[  374.670577] c5e0  00000000 0000009c 00000000 00000000 41101fb0 00000000 00eca180 00000000
[  374.670582] c600  00000000 00000000 40e9f810 00000000 00000005 00000000 1654b680 00000000
[  374.670585] 
[  374.670585] r20: 0xcf08c0:
[  374.670590] 08c0  2065726f 6f666e69 74616d72 2e6e6f69 65724720 796c7461 64657220 73656375
[  374.670596] 08e0  616f6c20 676e6964 6d697420 6f207365 6c70206e 6f667461 20736d72 68746977
[  374.670602] 0900  6f6c7320 69642077 61206b73 73656363 00002e73 00000000 68636143 6f432065
[  374.670607] 0920  49206572 206f666e 656c6946 00000073 72727543 20746e65 65726f43 00000000
[  374.670614] 0940  72617453 69442074 74636572 0079726f 72617453 6f632074 77206572 6f687469
[  374.670620] 0960  63207475 65746e6f 002e746e 00000000 72617453 6f432074 00006572 00000000
[  374.670625] 0980  65726f43 776f4420 616f6c6e 00726564 66726550 206d726f 6c66666f 20656e69
[  374.670631] 09a0  6e69616d 616e6574 2065636e 6b736174 6e6f2073 736e6920 6c6c6174 63206465
[  374.670634] 
[  374.670634] r22: 0x40ebce60:
[  374.670640] ce60  00000000 00000000 00000051 00000000 00000000 00000000 00000000 00000000
[  374.670645] ce80  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  374.670650] cea0  00000000 00000000 00000000 00000000 00000000 00000000 00000021 00000000
[  374.670656] cec0  646e735f 6d63705f 756c705f 706f5f67 69006e65 7475706e 00000021 00000000
[  374.670661] cee0  41531470 00000000 000000ff 00000000 00000001 00000000 00000021 00000000
[  374.670667] cf00  8105f000 0000007f 00000000 00000000 00000020 00000000 00000051 00000000
[  374.670672] cf20  40f9f520 00000000 00000003 00000000 40f9f5b0 00000000 00000000 00000000
[  374.670678] cf40  00000000 00000000 40f9fad8 00000000 40ee0028 00000000 40ec9060 00000000
[  374.670682] 
[  374.670684] signo: 11
[  374.670687] reg              value       pfn  reg              value       pfn
[  374.670695] r0 :  0000000000000000  --------  r1 :  0000007ffad1bb38     783a7
[  374.670699] r2 :  0000000000000000  --------  r3 :  00000000000000b3  --------
[  374.670704] r4 :  0000000000000000  --------  r5 :  00000000004e0520     568d8
[  374.670709] r6 :  0000000000002dc7  --------  r7 :  0204100a001b1101  --------
[  374.670714] r8 :  0000000000000001  --------  r9 :  7f7f7f7f7f7f7f7f  --------
[  374.670719] r10:  ffffffffffa28458  --------  r11:  0101010101010101  --------
[  374.670723] r12:  0000000000000006  --------  r13:  0000000000000000  --------
[  374.670729] r14:  01111b000a100402  --------  r15:  0000000041101fb0     3ac39
[  374.670736] r16:  00000000004e0520     568d8  r17:  0000007f822ce1e4     1fdd0
[  374.670740] r18:  000000000000ffff  --------  r19:  0000007ffad1c5a0     783a6
[  374.670745] r20:  0000000000cf0940     378af  r21:  0000000000000000  --------
[  374.670751] r22:  0000000040ebcee0     7835c  r23:  0000000000000001  --------
[  374.670755] r24:  0000000000000001  --------  r25:  0000000000000001  --------
[  374.670759] r26:  0000000000000000  --------  r27:  0000000000000000  --------
[  374.670763] r28:  0000000000000001  --------  r29:  0000000000000000  --------
[  374.670767] r30:  00000000004e0c2c     568d8  
[  374.670770] pc :  00000000004e0c34     568d8
[  374.670773] sp :  0000007ffad1bab0     783a7
[  374.670776] unused :  0000000000010098  --------
[  374.670780] offset :  0000000000000000
`

**Comment by spleen1981** [comment]
Is it the latest release? Did you test the previous one?
Which content/core are you trying to load?
Also please share a retroarch.log with debug level set both for frontend and core.

**Comment by turric4n** [comment]
Latest addon release and lastest Coreelec version.
It crash when I select Load Content in main menu (No content selected nor core)

**Comment by spleen1981** [comment]
Ok can you test the previous addon release and provide the log?

**Comment by turric4n** [comment]
Same problem

`[INFO] RetroArch 1.19.1 (Git 0792144)
[INFO] === Build =======================================
[INFO] Funcionalidades: ASIMD
[INFO] Version: 1.19.1
[INFO] Git: 0792144
[INFO] Built: Sep  4 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] Cannot resolve save file path.
[INFO] Cannot resolve save state file path.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Versión de la API libretro: 1, API usada en la compilación: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Starting threaded video driver..
[INFO] GLES version = 2.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Created shared context: 0x7fa01d1bd0.
[INFO] [EGL]: Current context: 0x7fa00e0ed0.
[INFO] [GL]: Found GL context: "fbdev_mali".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-G31.
[INFO] [GL]: Version: OpenGL ES 3.2 v1.r37p0-fbdev-g31-aarch64-fcd711257-28.f244e7e88dc61d961af5cc9c61677756.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Keyboard #0: "input_btrcu" (/dev/input/event1).
[INFO] [udev]: Keyboard #1: "meson-ir" (/dev/input/event4).
[INFO] [udev]: Keyboard #2: "input_ethrcu" (/dev/input/event3).
[INFO] [udev]: Keyboard #3: "vad_keypad" (/dev/input/event2).
[INFO] [udev]: Keyboard #4: "cec_input" (/dev/input/event0).
[INFO] [udev]: Keyboard #5: "Xbox Wireless Controller" (/dev/input/event6).
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[WARN] [udev]: Mouse grab/ungrab feature unavailable.
[INFO] [ALSA] Using ALSA version 1.2.13
[INFO] [ALSA]: Using S16_LE sample format for PLAYBACK device "sysdefault:CARD=AMLAUGESOUND"
[INFO] [ALSA]: Period: 4 periods per buffer (768 frames, 3072 bytes)
[INFO] [ALSA]: Buffer size: 3072 frames (12288 bytes)
[INFO] [ALSA]: Can pause: yes.
[INFO] [ALSA]: Initialized PLAYBACK device "sysdefault:CARD=AMLAUGESOUND"
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [ALSA] Using ALSA version 1.2.13
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Autoconf]: Se ha configurado Xbox Wireless Controller (xpadneo) en el puerto 1.
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed.
[INFO] [Playlist]: Cargando historial: "/storage/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Cargando historial: "/storage/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Cargando historial: "/storage/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: Cargando historial: "/storage/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Cargando favoritos: "/storage/.config/retroarch/content_favorites.lpl".
`

**Comment by spleen1981** [comment]
This is info level, please set **debug** level both for frontend and core, and attach the `retroarch.log` file, no one-row copy and paste please.
Also be sure to get the log immediatly after the crash.
Please also save to a file `dmesg`  and `journalctl -a -b -0` after the issue occurs, and attach the files here.

**Comment by turric4n** [comment]
[dmesg.log](https://github.com/user-attachments/files/18154080/dmesg.log)
[hw.log](https://github.com/user-attachments/files/18154081/hw.log)
[journal.log](https://github.com/user-attachments/files/18154082/journal.log)
[retroarch.log](https://github.com/user-attachments/files/18154083/retroarch.log)
[uname.log](https://github.com/user-attachments/files/18154085/uname.log)

Here we go

**Comment by spleen1981** [comment]
Can't replicate this, though with S905X3 and an older CE22 nightly.
Do you reach the point where the drive list is shown or you just select Load content and the crash occurs?
Can you disable the remote rom folder option from the addon options?
Did you try with a different menu driver?
If you launch retroarch from the cli does it work? e.g. `retroarch.start -L .kodi/addons/script.retroarch.launcher.Amlogic-ng.arm/lib/libretro/scummvm_libretro.so`

**Comment by turric4n** [comment]
Crash inmediatly when Load Content clicked, no drive list
Disabled and just crashed again
Crash with every driver
Launched from ssh also fails : 
`retroarch.start -L .kodi/addons/script.retroarch.launcher.Amlogic-ng.arm/lib/libretro/scummvm_libretro.so
ALSA lib /home/docker/build_dir/CoreELEC-22/build.CoreELEC-Amlogic-no.aarch64-22/build/alsa-lib-1.2.13/src/seq/seq_hw.c:531:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
/storage/.kodi/addons/script.retroarch.launcher.Amlogic-no.aarch64/bin/retroarch.start: line 306: 251605 Segmentation fault      (core dumped) $RA_EXE $RA_PARAMS "$@"
`
This is working : RetroPad

**Comment by turric4n** [comment]
It's very strange but Ozone works, no segmentation faults here. Now I have another problem, cores aren't working, Not avaliable cores. I'm going to reinstall the plugin entirely.
