### ISSUE TITLE
Import roms via SMB

### ISSUE THREAD

**Issue by flutejoust** [spleen1981/retroarch-kodi-addon-CoreELEC#8]
I’ve been trying to use this feature:

Use remote location (e.g. SMB) as roms folder. Remote path to be as follows //server_IP/path_to_roms_folder

Sorry if I’m missing something obvious, but how do I get it to work? I can’t find a setting to enable it, and I’m wary of messing with the cfg without knowing what I’m doing. 

Thanks!

**Comment by spleen1981** [comment]
Hi, no need to modify any cfg file.
You just go to the addon settings within kodi, under "Paths" submenu, turn on "Mount remote path for RetroArch ROMs", and set user,  password and remote path as in the example above.
If everything worked, remote path will be mounted as `/storage/roms` and automatically loaded in retroach as default roms folder.

**Comment by flutejoust** [comment]
Thanks, I appreciate your help.
