### ISSUE TITLE
roms stored on SMB share not accessible unless SAMBA server protocol forced to accept CORE connections

### ISSUE THREAD

**Issue by adr3nal1n** [spleen1981/retroarch-kodi-addon-CoreELEC#9]
Hi,

I have just switched to accessing roms from a SAMBA (SMB) share, rather than local storage,

I entered the rom path in the add-on settings with //ip_address/sharename and entered the username and password for the share, but when I launched the add-on it didn't map the SMB share to /storage/roms

I ssh'd into the coreelec box and tested manually mounting the smb share from the command line and it also failed with "operation not permitted". I then tried again but this time specified the option "-o vers=2.0" and it mounted successfully.

I couldn't see a way to set the version to use in the add-on, so for now, I have set the below in the global section of my smb.conf on my linux fileserver, as the add-on seems to default to using smb version 1 to mount the share. (From Samba v4.11 onwards, the default min protocol is version 2.0 This has been introduced to prevent ransomware attacks)

```
[global]
server min protocol = CORE
```

Would it be possible please, in a future release, to allow the user to specify the minimum smb version in the add-on settings?

Note that I did also check the SMB client settings in Kodi and I did set the minimum protocol version to SMB2, but it made no difference to the issue and the only resolution was to force my samba server config to serve a minimum of version 1 (aka CORE)

Thanks ever so much for maintaining this superb add-on for coreelec.

**Comment by spleen1981** [comment]
good point, option added in settings for next release
